const colors=[["#ff5f6d","#ffc371"],["#7048e8","#4dabf7"],["#0ca678","#96f2d7"],["#f06595","#fcc2d7"],["#495057","#adb5bd"]];
const norm=s=>(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const fmt=n=>new Intl.NumberFormat("en-US").format(n);
function initials(s){return s.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
async function appleSearch(term,entity="song"){const u="https://itunes.apple.com/search?term="+encodeURIComponent(term)+"&entity="+entity+"&limit=8&country=us";const r=await fetch(u,{mode:"cors"});if(!r.ok)throw new Error("Apple");return r.json()}
function pick(results,row){const a=norm(row.artist),s=norm(row.song.replace(/\s*\([^)]*\)\s*/g," "));return results.find(x=>norm(x.artistName)===a&&norm(x.trackName)===s)||results.find(x=>norm(x.artistName).includes(a.split(" ")[0])&&norm(x.trackName).includes(s.split(" ").slice(0,3).join(" ")))||results.find(x=>norm(x.artistName).includes(a.split(" ")[0]))}
async function artwork(row){const key="appleArt:"+norm(row.artist+" "+row.song);const c=localStorage.getItem(key);if(c)return c==="__none__"?null:c;try{let d=await appleSearch(row.song+" "+row.artist);let h=pick(d.results||[],row);if(!h&&row.album){d=await appleSearch(row.album+" "+row.artist,"album");h=(d.results||[])[0]}const art=h?.artworkUrl100?.replace(/100x100bb/,"400x400bb")||null;localStorage.setItem(key,art||"__none__");return art}catch(e){return null}}
const top=window.DAEGON_WEEKLY.slice(0,5);
document.getElementById("heroSong").innerHTML=`<div class="hero-cover loading-art" id="heroCover">${initials(top[0].artist)}</div><div><small>#1 · GLOBAL</small><h3>${top[0].song}</h3><p>${top[0].artist} · ${fmt(top[0].streams)} streams</p></div>`;
document.getElementById("heroMiniList").innerHTML=top.slice(1,4).map(r=>`<div class="hero-mini-item"><b>#${r.rank}</b><span>${r.song} · ${r.artist}</span><em>${fmt(r.streams)}</em></div>`).join("");
document.getElementById("topFiveGrid").innerHTML=top.map((r,i)=>{const c=colors[i];return `<article class="top-five-card"><div class="top-five-cover loading-art" data-home-art="${r.rank}" style="--c1:${c[0]};--c2:${c[1]}">${initials(r.artist)}</div><span class="top-five-rank">#${r.rank} ${r.dif==="NEW"?"· NEW":""}</span><h3>${r.song}</h3><p>${r.artist}</p><footer><span>${fmt(r.streams)} streams</span><span>peak #${r.peak}</span></footer></article>`}).join("");
(async()=>{for(const r of top){const art=await artwork(r);const els=[...document.querySelectorAll('[data-home-art="'+r.rank+'"]')];if(r.rank===1)els.push(document.getElementById("heroCover"));els.forEach(el=>{if(!el)return;el.classList.remove("loading-art");if(art){el.style.backgroundImage='url("'+art+'")';el.classList.add("has-artwork")}})}})();
